### ISSUE TITLE
Reloading fails when filenames have uppercase letters

### ISSUE THREAD

**Issue by SolsticeShard** [robertwayne/cogwatch#14]
Hi, super awesome project! Was experimenting with this, and I found that I would always hit an extension reload error if any of my cog file names had an upper case letter as it looks like the reloading logic forces everything to be lower case. Not blocking as I can make sure all of my cog file names are lower but it took a decent bit of digging around to find that was the issue.

**Comment by robertwayne** [comment]
Thanks for mentioning this.

This should be fixed in the next release. The check was not actually doing anything - holdover code from a prior implementation I believe!

You can pull in the branch specifically with `pip install git+https://github.com/robertwayne/cogwatch@next` if you wish. It should "just work". :)
